language: android
dist: precise
jdk: oraclejdk8

# Android settings
android:
  components:
    - tools
    # Same version as specified in build.gradle

    # Build Tools version
    - build-tools-34.0.0

    # SDK version to compile against
    - android-33

   # Additional components
    - extra-android-m2repository

    # Specify a system image
    - sys-img-armeabi-v7a-android-21

  licenses:
    - '.+'
     
# Run before running the build script
before_script:
    - wget https://services.gradle.org/distributions/gradle-8.1-bin.zip
    - unzip gradle-8.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-8.1
    - export PATH=$GRADLE_HOME/bin:$PATH
    - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    
# Licenses to be accepted
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
